### PR TITLE
ICAP: talk to ICAP primitive to restart gateware

### LINKED ISSUE #1721: Reboot leads to inconsistent device state
# Bug Report

## One-Line Summary

`artiq_coremgmt reboot` does not actually reboot the device. Instead, the device is placed in an inconsistent state. 

### Steps to Reproduce

1. Run `artiq_coremgmt reboot`
2. Notice that the device is not responsive.

### Expected Behavior

Expect the device to restart.

### Actual (undesired) Behavior

The issue can be seen in the UART logs after running `artiq_coremgmt reboot`. The error seen is `panic at runtime/kernel.rs:11:9: attempted to start kernel CPU when it is already running`

UART logs: 
```
[2021-07-16 13:33:45] [    37.432861s]  INFO(runtime::mgmt): new connection from 10.236.50.50:59658
[2021-07-16 13:33:45] [    37.440786s]  WARN(runtime::mgmt): restarting
[2021-07-16 13:33:45] [     0.000009s]  INFO(runtime): ARTIQ runtime starting...
[2021-07-16 13:33:45] [     0.003932s]  INFO(runtime): software ident 6.7613.c4902be6;molecular_ions
[2021-07-16 13:33:45] [     0.010823s]  INFO(runtime): gateware ident 6.7613.c4902be6;molecular_ions
[2021-07-16 13:33:45] [     0.017750s]  INFO(runtime): log level set to INFO by default
[2021-07-16 13:33:45] [     0.023462s]  INFO(runtime): UART log level set to INFO by default
[2021-07-16 13:33:45] [     0.029843s]  INFO(runtime::rtio_clocking): using internal RTIO clock (by default)
[2021-07-16 13:33:45] [     0.307759s]  INFO(board_artiq::si5324): waiting for Si5324 lock...
[2021-07-16 13:33:47] [     2.108392s]  INFO(board_artiq::si5324):   ...locked
[2021-07-16 13:33:47] [     2.112441s]  INFO(runtime): network addresses: MAC=10-e2-d5-32-50-24 IPv4=10.236.50.51 IPv6-LL=fe80::12e2:d5ff:fe32:5024 IPv6=no configured address
[2021-07-16 13:33:47] [     2.127325s]  INFO(runtime::mgmt): management interface active
[2021-07-16 13:33:47] [     2.142188s]  INFO(runtime::session): accepting network sessions
[2021-07-16 13:33:47] [     2.157611s]  INFO(runtime::session): running startup kernel
[2021-07-16 13:33:47] panic at runtime/kernel.rs:11:9: attempted to start kernel CPU when it is already running
[2021-07-16 13:33:47] backtrace for software version 6.7613.c4902be6;molecular_ions:
[2021-07-16 13:33:47] 0x40046f34
[2021-07-16 13:33:47] 0x4001feb0
[2021-07-16 13:33:47] 0x4001fe5c
[2021-07-16 13:33:47] 0x4002ded4
[2021-07-16 13:33:47] 0x40033150
[2021-07-16 13:33:47] 0x40025e2c
[2021-07-16 13:33:47] 0x40025bc4
[2021-07-16 13:33:47] halting.
[2021-07-16 13:33:47] use `artiq_coremgmt config write -s panic_reset 1` to restart instead
```

### Your System (omit irrelevant parts)

* ARTIQ version: v6.7613.c4902be6
* Version of the gateware and runtime loaded in the core device:  v6.7613.c4902be6 
* Hardware involved: Kasli v1.1, Kasli v2.0, KC705

### PR DESCRIPTION
**Pull request by SidaChen1999**
# ARTIQ Pull Request

## Description of Changes
Deprecate the `artiq_coremgmt reboot` with `artiq_coremgmt flash start`. The firmware will use `csr` to trigger ICAP to restart the gateware.

### Related Issue
Closes #1721 

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
| ✓  | :sparkles: New feature |

### All Pull Requests

- [x] Use correct spelling and grammar.
- [x] Close/update issues.

### Code Changes

- [x] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [x] Test your changes or have someone test them. Mention what was tested and how.
- [x] Add and check docstrings and comments

### Documentation Changes

- [ ] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [x] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [x] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -16,7 +16,7 @@ __pycache__/
 /.coverage
 /artiq/test/lit/*/Output/
 /artiq/binaries
-/artiq/firmware/target/
+/artiq/firmware/**/target/
```
Comment (sbourdeauducq) [inline .gitignore:19]: Shouldn't be part of this PR (if it should be there at all).

File: artiq/firmware/libboard_misoc/lib.rs [hunk 2]
```diff
@@ -43,3 +43,5 @@ pub mod io_expander;
 pub mod net_settings;
 #[cfg(has_slave_fpga_cfg)]
 pub mod slave_fpga;
+#[cfg(any(soc_platform = "kasli", soc_platform = "metlino"))]
+pub mod flash;
```
Comment (sbourdeauducq) [inline artiq/firmware/libboard_misoc/lib.rs:47]: This module shouldn't be called flash if all it does is talk to the ICAP.
Do we need a module for just that function?

File: artiq/firmware/libboard_misoc/flash.rs [hunk 3]
```diff
@@ -0,0 +1,10 @@
+mod imp {
+    use csr;
+
+    pub unsafe fn reload () -> ! {
+        csr::icap::iprog_write(1);
+        loop {}
+    }
+}
+
+pub use self::imp::*;
```
Comment (sbourdeauducq) [inline artiq/firmware/libboard_misoc/flash.rs:10]: Simply put the functions at the top level.
That pattern is only used for selecting different implementations using ``#[cfg()]`` but here you are already putting the ``#[cfg()]`` in ``lib.rs``.

File: artiq/frontend/artiq_coremgmt.py [hunk 4]
```diff
@@ -82,10 +82,15 @@ def get_argparser():
 
     subparsers.add_parser("erase", help="fully erase core device config")
 
+    # flash
+    t_flash = tools.add_parser("flash",
+                        help="ARTIQ reboot tool though internet")
```
Comment (sbourdeauducq) [inline artiq/frontend/artiq_coremgmt.py:87]: It's not internet.

File: artiq/frontend/artiq_coremgmt.py [hunk 5]
```diff
@@ -82,10 +82,15 @@ def get_argparser():
...
+
+    t_flash.add_argument("action", metavar="ACTION", nargs="*",
+                        default=[],
+                        help="actions to perform, choose from: start")
+    
     # booting
-    t_boot = tools.add_parser("reboot",
-                              help="reboot the currently running firmware")
-
     t_hotswap = tools.add_parser("hotswap",
```
Comment (sbourdeauducq) [inline artiq/frontend/artiq_coremgmt.py:94]: Remove this one, it doesn't work correctly. Though that can go into a separate PR.

File: artiq/frontend/artiq_coremgmt.py [hunk 6]
```diff
@@ -82,10 +82,15 @@ def get_argparser():
 
     subparsers.add_parser("erase", help="fully erase core device config")
 
+    # flash
+    t_flash = tools.add_parser("flash",
+                        help="ARTIQ reboot tool though internet")
+
+    t_flash.add_argument("action", metavar="ACTION", nargs="*",
```
Comment (sbourdeauducq) [inline artiq/frontend/artiq_coremgmt.py:89]: Why not keep the old reboot option, at least for now?

File: .gitignore (hunk 1 above)
Comment (SidaChen1999) [reply .gitignore:19]: Should I open a new PR for this line?

Comment (sbourdeauducq) [reply .gitignore:19]: If you need it. But I'm not sure what problem this fixes.

File: artiq/firmware/libboard_misoc/lib.rs (hunk 2 above)
Comment (SidaChen1999) [reply artiq/firmware/libboard_misoc/lib.rs:47]: Because later I'll put the flash functions into this file. Should I put it into `or1k/boot.rs`?

Comment (sbourdeauducq) [reply artiq/firmware/libboard_misoc/lib.rs:47]: It's not OR1K-specific. ``flash`` is also a bad name because there's already ``spiflash``.

File: artiq/firmware/libboard_misoc/flash.rs (hunk 3 above)
Comment (SidaChen1999) [reply artiq/firmware/libboard_misoc/flash.rs:10]: Here comes a problem. The main of firmware used the previous reboot function, and every board can use that. But I'm not sure whether every board can use ICAP.

Comment (sbourdeauducq) [reply artiq/firmware/libboard_misoc/flash.rs:10]: The reboot currently is broken and should not be used. Not supporting reboot at all on those boards is better than having a broken reboot.

File: artiq/firmware/libboard_misoc/lib.rs (hunk 2 above)
Comment (SidaChen1999) [reply artiq/firmware/libboard_misoc/lib.rs:47]: Then, I think it's better to keep this file at this place. How about renaming it as `flash_tools`?

File: artiq/firmware/libboard_misoc/flash.rs (hunk 3 above)
Comment (SidaChen1999) [reply artiq/firmware/libboard_misoc/flash.rs:10]: Understand. Then I will disable the reboot function on those boards.

File: artiq/firmware/libboard_misoc/lib.rs (hunk 2 above)
Comment (sbourdeauducq) [reply artiq/firmware/libboard_misoc/lib.rs]: Why not simply add to spiflash?

File: artiq/frontend/artiq_coremgmt.py [hunk 7]
```diff
@@ -176,12 +170,9 @@ def main():
...
         if args.action == "erase":
             mgmt.config_erase()
-
-    if args.tool == "reboot":
-        mgmt.reboot()
-
-    if args.tool == "hotswap":
-        mgmt.hotswap(args.image.read())
+        
+        if args.tool == "reboot":
```
Comment (sbourdeauducq) [inline artiq/frontend/artiq_coremgmt.py:174]: indentation
